name: Unit tests

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Core Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Enable Corepack
        run: corepack enable

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install
        run: |
          yarn

      - name: test
        run: |
          yarn test

      - name: lint
        run: |
          yarn lint

      - name: chromatic
        run: |
          yarn chromatic
